---

# create docker config directoy
- name: create docker config directory
  file:
    path: /etc/docker
    state: directory
    mode: 0600
    owner: root
    group: root

- name: configure docker daemon.json
  docker_common_config:
    state: present
    log_driver: "{{ docker_config_log_driver }}"
    log_opts: "{{ docker_config_log_opts }}"
    log_level: "{{ docker_config_log_level }}"
    data_root: "{{ docker_config_data_root }}"
    max_concurrent_downloads: "{{ docker_config_max_concurrent_downloads }}"
    max_concurrent_uploads: "{{ docker_config_max_concurrent_uploads }}"
    debug: "{{ docker_config_debug }}"
    selinux_enabled: "{{ docker_config_selinux_enabled }}"
    experimental: "{{ docker_config_experimental }}"
    group: "{{ docker_config_group }}"
    bridge: "{{ docker_config_bridge | default(omit) }}"
    bip: "{{ docker_config_bip }}"
    fixed_cidr: "{{ docker_config_fixed_cidr }}"
    fixed_cidr_v6: "{{ docker_config_fixed_cidr_v6 }}"
    default_gateway: "{{ docker_config_default_gateway }}"
    default_gateway_v6: "{{ docker_config_default_gateway_v6 }}"
    insecure_registries: "{{ docker_config_insecure_registries }}"
    ip: "{{ docker_config_ip }}"
  register: _changed_docker_configuration
  notify: daemon-reload

# push client config if enabled
- name: create docker client config directory
  file:
    state: directory
    path: "{{ docker_client_config_location | dirname }}"
    mode: 0750
  when: docker_client_config_enabled

- name: configure docker client config.json
  template:
    src: "config.json.j2"
    dest: "{{ docker_client_config_location }}"
    mode: 0440
  when: docker_client_config_enabled

# configure proxy settings if enabled
- name: create dropin directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: "directory"
    mode: 0750
    owner: root
    group: root

- name: add systemd dropin to using configuration
  template:
    src: overwrite.conf.j2
    dest: "/etc/systemd/system/docker.service.d/overwrite.conf"
    mode: 0640
    owner: root
    group: root
  notify: daemon-reload
  when:
    - _changed_docker_configuration is defined
    - _changed_docker_configuration.changed is defined
    - _changed_docker_configuration.changed

- name: add systemd dropin for proxy
  template:
    src: "proxy.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/proxy.conf"
    mode: 0640
    owner: root
    group: root
  when: docker_proxy_enabled
  notify: daemon-reload
