---

- name: Remove default packaged docker
  package:
    name: [docker, docker-engine]
    state: absent

- name: Install Docker
  package:
    name: docker-ce
    state: "{{ docker_state }}"
    update_cache: true
