---

- name: Install Official Docker Repositories (redhat)
  yum_repository:
    name: "docker-ce-{{ item.channel }}"
    description: Docker Repository Stable Channel
    # https://download.docker.com/linux/centos/$releasever/$basearch/stable
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/{{ item.channel }}"
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
    enabled: "{{ item.enabled }}"
  with_items:
    - channel: stable
      enabled: "{{ docker_repo_channel_stable_enabled }}"
    - channel: nightly
      enabled: "{{ docker_repo_channel_nightly_enabled }}"
    - channel: test
      enabled: "{{ docker_repo_channel_test_enabled }}"
  when:
    - docker_repo_enabled
