---

- name: restart-docker
  service:
    name: docker
    state: restarted

- name: daemon-reload
  systemd:
    daemon_reload: true
    force: true
  notify: restart docker
  when:
    - ansible_service_mgr == 'systemd'
