---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:

    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

    - name: update package cache
      package:
        update_cache: true

    - name: install python3-apt on debian based
      package:
        name:
          - python3-apt
        state: present
      when:
        - ansible_os_family | lower == 'debian'

    - name: install netstat for archlinux or debian based
      package:
        name:
          - net-tools
          - iproute2
        state: present
      when:
        - ansible_os_family | lower in [ 'archlinux', 'debian' ]

    - name: install netstat for redhat based < 8
      package:
        name:
          - net-tools
          - iproute
        state: present
      when:
        - ansible_os_family | lower == 'redhat'
        - ansible_distribution_major_version | int == 7
